language: cpp

dist: bionic
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - BUILD_STATIC_QRC=ON
  - BUILD_STATIC_QRC=OFF

addons:
  apt:
    sources:
      - sourceline: "ppa:beineri/opt-qt-5.14.2-bionic"
    packages:
      - cmake
      - qt514base
      - qt514declarative
      - qt514graphicaleffects
      - qt514quickcontrols2
      - mesa-common-dev
      - libgl1-mesa-dev
  homebrew:
    update: true
    packages:
      - qt5

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake;
    fi

install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew link qt5 --force;
    fi

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      export PATH=$PATH:/opt/qt512/bin;
    fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      export PATH=/usr/local/opt/qt/bin:$PATH; 
    fi

script:
  - which qmake
  - qmake --version
  - g++ --version
  - cmake --version
  - mkdir build && cd build
  - cmake .. -DBUILD_STATIC_QRC=${BUILD_STATIC_QRC}
  - make VERBOSE=1

notifications:
  email: false
